#!/bin/bash
# vim: syntax=sh:

set -e

BASEDIR="$(dirname "${BASH_SOURCE[0]}")"
source "${BASEDIR}/install-conf/utils.sh"

function update_self() {
    log "Pull/update dotfiles"

    # "git pull --autostash" doesn't support in old git version.
    git pull --autostash 2>/dev/null || git pull
}

function update_submodule() {
    #zprezto-update

    # Sync URL change from upstream
    git submodule sync --recursive
    # Pull submodule
    git submodule update --remote
    # Pull submodule (seems doesn't work)
    #git submodule update --init --remote

    # Reset submodule of submodule to pinned commit
    git submodule foreach git submodule update --init

    # backup
    #git submodule update --init --remote -f
}

function restore_submodule() {
    git submodule sync --recursive
    git submodule update --init --recursive
}


function main() {
    pushd "${BASEDIR}"

    update_self
    update_submodule

    # Remove fzf configs
    rm -f ~/.fzf.bash ~/.fzf.zsh
    rm -rf modules/fzf/

    # update vim plugin
    . config/vim/update

    popd
}

main
