" TODO(cebrusfs): copyright {
" vim: set sw=4 ts=4 sts=4 et foldmarker={,} foldlevel=0 foldmethod=marker syntax=vim:
" }

" General {
    filetype plugin indent on

    set shortmess+=filnxtToOmr          " Abbrev. of messages (avoids 'hit enter')
    set virtualedit=onemore             " Allow for cursor beyond last character

    set history=1000                    " Store a ton of history (default is 20)

    set iskeyword-=.                    " '.' is an end of word designator
    set iskeyword-=#                    " '#' is an end of word designator
    set iskeyword-=-                    " '-' is an end of word designator

    " allow backspacing over everything in insert mode
    set backspace=2
    " auto read when file is changed from outside
    set autoread

    " swapfile directory
    set directory^=~/.vimfiles/swap,/tmp2

    set backupdir^=~/.vimfiles/backup,/tmp2
    set backup

    set undodir^=~/.vimfiles/undo,/tmp2
    set undofile

    set clipboard^=unnamed,unnamedplus  " share clipboard with system side
" }

" Autocmd {
    augroup MyAutoCmd
        autocmd!
    augroup END
" }

" Searching {
    set incsearch           " move to matched pattern
    set hlsearch            " search highlighting
    set ignorecase		    " ignore case
    set smartcase		    " ignore case if search pattern is all lowercase
" }

" Encoding {
    scriptencoding utf-8

    set fileformat=unix
    set fileformats=unix,dos

    set encoding=utf-8

    set fileencoding=utf-8
    set fileencodings=ucs-bom,utf-8,big5,cp936,gb18030,latin1
" }

" User Interface {
    set showmode		    " show current mode
    set ruler		        " show the cursor position all the time
    set number              " line number
    set showmatch		    " cursor shows matching bracket
    set nocursorline        " no underline the current line

    set foldmethod=marker   " fold

    " Auto complete menu {
        " disable preview window when completing (default: menu,preview)
        set completeopt-=preview
        set wildmenu            " use menu when completing
        set wildchar=<TAB>	    " start wild expansion in the command line using

        set wildignore^=*.o,*.class,*.pyc " ignore these files while expanding wild chars
    " }

    " Linebreaking Settings {
        set wrap                " auto wrap when line is too long (default: on)
        set nolinebreak         " no auto line breaking (default: off)
        set nolist
    " }
" }

" Programming {
    set autoindent		    " auto indentation
    set copyindent		    " copy the previous indentation on autoindenting
    set smarttab		    " insert tabs on the start of a line according to
                            " context
    set expandtab           " use spaces instead of tabs

    " 1 tab == 4 spaces
    set tabstop=4
    set shiftwidth=4
    set softtabstop=4

    " auto wrap the long lines
    set textwidth=80

    " resource when write to vimrc
    autocmd MyAutoCmd BufWritePost .vimrc nested source $MYVIMRC
" }

" Key mapping {
    " Trying space as leader key
    let mapleader="\<Space>"
    let maplocalleader="\<Space>"

    " Quick load/save
    nnoremap <Leader>w :w<CR>
    nnoremap <Leader>e :e<CR>

    " Copy/paste using system clipboard
    "noremap <Leader>y "+y
    "noremap <Leader>d "+d
    "noremap <Leader>p "+p
    "noremap <Leader>P "+P

    " Move between tabs (FIXME)
    "default: gT or ctrl-PageUp
    nnoremap <C-h> :tabprevious<CR>
    "default: gt or ctrl-PageDown
    nnoremap <C-l> :tabnext<CR>

    " Move between wrapped line
    nnoremap <Down> g<Down>
    nnoremap <Up> g<Up>

    " NERDTree: Shift + Tab
    nnoremap <S-Tab> :NERDTreeToggle<CR>

    " NERDComment: \
    nmap <Bslash> <Plug>NERDCommenterToggle
    xmap <Bslash> <Plug>NERDCommenterToggle

    " Code folding options
    " nnoremap <Leader>f0 :set foldlevel=0<CR>
    " nnoremap <Leader>f1 :set foldlevel=1<CR>
    " nnoremap <Leader>f2 :set foldlevel=2<CR>
    " nnoremap <Leader>f3 :set foldlevel=3<CR>
    " nnoremap <Leader>f4 :set foldlevel=4<CR>
    " nnoremap <Leader>f5 :set foldlevel=5<CR>
    " nnoremap <Leader>f6 :set foldlevel=6<CR>
    " nnoremap <Leader>f7 :set foldlevel=7<CR>
    " nnoremap <Leader>f8 :set foldlevel=8<CR>
    " nnoremap <Leader>f9 :set foldlevel=9<CR>

    " Syntastic
    "nnoremap <silent> <Leader>e :Errors<CR>
    "nnoremap <Leader>s :SyntasticToggleMode<CR>

    " Start interactive EasyAlign in visual mode (e.g. vipga)
    xmap <Leader>a <Plug>(EasyAlign)
    " Start interactive EasyAlign for a motion/text object (e.g. gaip)
    nmap <Leader>a <Plug>(EasyAlign)

    " YouCompleteMe
    nnoremap <leader>g :YcmCompleter GoTo<CR>

    " fzf {
        let g:fzf_command_prefix = 'FZF'

        let g:fzf_action = {
              \ 'ctrl-t': 'tab split',
              \ 'ctrl-s': 'botright split',
              \ 'ctrl-v': 'botright vsplit' }

        command! -bang -nargs=* FZFRg
          \ call fzf#vim#grep(
          \   'rg --no-heading --vimgrep --colors path:style:bold --colors path:fg:blue'.
          \   ' --colors line:style:bold --colors line:fg:black --colors match:fg:green'.
          \   ' --color=always '.shellescape(<q-args>), 1,
          \   <bang>0 ? fzf#vim#with_preview('up:60%')
          \           : fzf#vim#with_preview('right:50%:hidden', '?'),
          \   <bang>0)

        " Search in current buffer
        nnoremap <Leader>/ :FZFBLines<CR>
        nnoremap <Leader><Space>/ :FZFBLines <C-R><C-W><CR>

        " Search in opened buffers
        nnoremap <Leader>. :FZFLines<CR>
        nnoremap <Leader><Space>. :FZFLines <C-R><C-W><CR>

        " Search file
        nnoremap <Leader>f :FZF<CR>

        " Search file contents
        nnoremap <Leader>r :FZFRg<CR>
        nnoremap <Leader><Space>r :FZFRg <C-R><C-W><CR>

        " Search in git commits
        nnoremap <Leader>c :FZFBCommits<CR>

        " vim command history search
        nnoremap <Leader>; :FZFHistory<CR>
    " }

    " fugitive {
        nnoremap <Leader>gs :Gstatus<CR>
        nnoremap <Leader>gd :Gdiff<CR>
        nnoremap <Leader>gb :Gblame<CR>
    " }
" }

" Vundle Plugins {
    if filereadable(expand('~/.vim/vimrc.bundles'))
        let g:plug_timeout=300
        source ~/.vim/vimrc.bundles
    endif
" }

" Colorscheme {
    function! HasColorScheme(name)
        " a vim function to check whether the colorscheme exsits
        " usage: if HasColorScheme('schemename')
        let pat='colors/'.a:name.'.vim'
        return !empty(globpath(&rtp, pat))
    endfunction


    if (HasColorScheme('base16-tomorrow-night-cebrusfs') && has('termguicolors'))
        set termguicolors

        let g:airline_theme='tomorrow'
        colorscheme base16-tomorrow-night-cebrusfs
    else
        colorscheme desert
    endif


    " Syntax highlighting
    syntax on
" }

" Plugin Settings {
    " YouCompleteMe {
        let g:ycm_always_populate_location_list=1

        let g:ycm_confirm_extra_conf=0
        let g:ycm_global_ycm_extra_conf='~/.vim/ycm_extra_conf.py'

        let g:ycm_semantic_triggers={'haskell' : ['.']}
    " }

    " nerdcommenter {
        " Add spaces after comment delimiters by default
        let g:NERDSpaceDelims = 1

        let g:NERDCustomDelimiters={
            \   'armasm': {'left': '@'},
            \   'c': { 'left': '//'}
            \}
    " }

    " vim-airline {
        let g:Powerline_symbols='fancy'
        set laststatus=2
    " }

    " vim-pandoc {
        let g:pandoc#syntax#conceal#urls = 1
    " }

    " vim-polyglot {
        " For js file, only contains @jsx pragma will be regonized as jsx
        let g:jsx_pragma_required = 1
    " }

    " rainbow {
        " 0: disable
        let g:rainbow_conf = {
            \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
            \   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
            \   'operators': '_,_',
            \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
            \   'separately': {
            \       '*': {},
            \       'tex': {
            \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
            \       },
            \       'lisp': {
            \           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
            \       },
            \       'vim': {
            \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
            \       },
            \       'html': {
            \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
            \       },
            \       'css': 0,
            \       'c': 0,
            \       'cpp': 0,
            \       'python': 0
            \   }
            \}
        let g:rainbow_active = 1
    " }

    " vim-nerdtree {
        let NERDTreeIgnore=['\~$', '\.o$', '\.pyc$']
    " }

    " vim-nerdtree-tabs {
        let g:nerdtree_tabs_open_on_gui_startup=0
    " }

    " vim-indent-guides {
        let g:indent_guides_auto_colors=0
        autocmd VimEnter,Colorscheme * highlight IndentGuidesOdd  guibg=grey30   ctermbg=234
        autocmd VimEnter,Colorscheme * highlight IndentGuidesEven guibg=grey15   ctermbg=236
        let g:indent_guides_guide_size=1
        let g:indent_guides_enable_on_vim_startup=1
    " }
" }
