#!/bin/bash

BASEDIR="$(dirname "${BASH_SOURCE[0]}")"

# git pull
# curl -fLo "$BASEDIR/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

function update() {
    "$1" +PlugClean +PlugUpdate +CocUpdateSync +qa
}

update vim
update nvim


