" vim: ts=4 sts=4 sw=4 et foldmarker={,} foldlevel=0 foldmethod=marker

scriptencoding utf-8

execute 'source' fnameescape(expand('<sfile>:p:h') . '/common.vim')

" Vim plugins {
call plug#begin('~/.vim/plugged')

" Color Scheme {
    Plug 'tomasiser/vim-code-dark'
" }

" Git {
    Plug 'tpope/vim-fugitive'

    nmap <Leader>g <Plug>(key-git)
    nnoremap <silent> <Plug>(key-git)s :<C-u>Git<CR>
    nnoremap <silent> <Plug>(key-git)d :<C-u>Gdiff<CR>
    nnoremap <silent> <Plug>(key-git)b :<C-u>Git blame<CR>
    nnoremap <silent> <Plug>(key-git)m :<C-u>Git mergetool<CR>
" }

" Editing helpers {
    Plug 'junegunn/vim-easy-align'
    Plug 'preservim/nerdcommenter'
    Plug 'tpope/vim-endwise'

    xmap <Leader>- <Plug>(EasyAlign)
    nmap <Leader>- <Plug>(EasyAlign)

    let g:NERDCreateDefaultMappings = 0
    let g:NERDSpaceDelims = 1
    let g:NERDCompactSexyComs = 1
    let g:NERDCommentEmptyLines = 1
    let g:NERDToggleCheckAllLines = 1
    let g:NERDCustomDelimiters = {
        \'armasm': {'left': '@'},
    \}

    nmap <Bslash> <Plug>NERDCommenterToggle
    xmap <Bslash> <Plug>NERDCommenterToggle
" }

" Remote clipboard {
    Plug 'ShikChen/osc52.vim'

    vnoremap Y y:call SendViaOSC52(getreg('"'))<CR>
" }

call plug#end()
" }

" Editor responsibility {
" Vim stays a minimal fallback editor; Neovim owns the richer
" LSP/completion/search workflows.
" }

" Native whitespace display {
    " Show tabs, trailing spaces, and non-breaking spaces in Vim. Neovim uses
    " `mini.trailspace` for trailing whitespace.
    set list
    set listchars=tab:>\ ,trail:-,nbsp:+
" }

" Colorscheme settings {
    colorscheme codedark
" }
