#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Meng-Huan Yu"
email = "2252236+cebrusfs@users.noreply.github.com"

[ui]
default-command = "log"

# Output git-format diffs so that `delta` can properly parse and style them
diff-formatter = ":git"

# As of jj v0.36.0, the $PAGER environment variable is ignored.
# The pager must be explicitly configured here to use 'delta'.
pager = "delta"

# Editors
diff-editor = ":builtin"

# Used for 3-way merge conflict resolution (e.g., `jj resolve`)
merge-editor = "vimdiff"
show-cryptographic-signatures = true

[git]
# Prevent upload
private-commits = 'blacklist()'

# Sign on push, work together with behavior = "drop"
# sign-on-push = true

# Automatically track all branches/bookmarks on `origin` remote
[remotes.origin]
auto-track-bookmarks = "glob:*"

[aliases]
blame = ["file", "annotate"]
bl = ["blame"]

[revset-aliases]
# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
'wip()' = 'description(glob:"wip:*")'
'private()' = 'description(glob:"private:*") | description(glob:"DO.?NOT.?SUBMIT:*")'
'blacklist()' = 'wip() | private()'

[signing]
key = "~/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "~/.config/git/allowed_signers"

[template-aliases]
diff_counts = "self.diff().summary()"

# Enable signing
# backend = "ssh"
# behavior = "own"
