# vim: ts=2: sts=2: sw=2:

#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {


# Print the message.
cat <<-EOF

Bye!
EOF

} >&2
