# vim: ts=2: sts=2: sw=2:

#
# Defines environment variables.
# This file is sourced by all instances of Zsh, and thus,
# it should be kept as small as possible and should only define environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# OSX
# tar: Do NOT pack UI configuration file (e.g. .DS_Store)
export COPYFILE_DISABLE=true
# Homebrew: cask: Change default app install directory
export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

# Java SDK paths
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

# GPG
export GPG_TTY=`tty`

# Corp tool configuration
# roadwarrior (rw)
export AUTH_CHECK_REMAINING=true
export AUTH_TMUX=true
export AUTH_TMUX_ITERM=true
export AUTH_TMUX_SESSION=tmux-main

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
