# vim: syntax=zsh:

#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
ZDOT_DIR=${ZDOT_DIR:-$HOME/.dotfiles/}
ZPREZTO_DIR=${ZPREZTO_DIR:-$ZDOT_DIR/modules/prezto}
INIT_PATH="$ZPREZTO_DIR/init.zsh"
if [[ -s "$INIT_PATH" ]]; then
    source "$INIT_PATH"
fi


# Warning for old configuration
if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
    echo "[WARN] $HOME/.zprezto is exists, use the following command to delete it"
    echo "    rm -rf $HOME/.zprezto"
fi


#
# Customize to your needs...
#

function check_command () {
    command -v $1 >/dev/null
}

bindkey "^R" history-incremental-pattern-search-backward
bindkey -M vicmd '/' history-incremental-pattern-search-backward

# overwrite when using file redirect (>) to existed file
setopt clobber

# Disable ctrl-s for stop output by terminal.
stty -ixon

#
# ls colors
#
# Tool: https://geoff.greer.fm/lscolors/

# BSD (mac)
export LSCOLORS="Gxfxcxdxbxegedabagacad"
# Linux
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
# zsh (use Linux format)
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}


#
# Alias
#

alias rm='rm -r'
alias cp='cp -rv'
alias objdump='objdump -M intel'
alias gistp='gist -p'

# Use 'colordiff' instead of 'diff'
check_command colordiff && alias diff='colordiff'

# Better rg wrapper for 'find'
function rgg () {
    rg --colors=path:none --files -g "*$1*"
}

# Use 'tmx2' instead of 'tmux' when available
check_command tmx2 && alias tmux='tmx2'

# Irssi
# TODO: remove this, given I'm using screen-256color in tmux now
# irssi under 'xterm-256color' (used by tmux) will refresh only half of screen, set to screen-256color to fix this
#alias irssi='TERM=screen-256color irssi'

# SSH
# Hook ssh to change tmux window name
function ssh() {
    local window_name
    window_name="$1"

    if [[ "$#" != 1 || "${window_name:0:1}" == "-"  ]]; then
        window_name="ssh"
    fi

    # set window name to hostname if we are in the tmux
    if [[ -n "$TMUX" ]]; then
        tmux rename-window "${window_name}"
    fi

    local err_count=0
    while true; do
        local start_time=$(date +%s)

        /usr/bin/env ssh "$@"

        # break if no error
        local return_code=$?
        [[ $return_code -ne 255 ]] && break

        local end_time=$(date +%s)

        local time_diff=$(( $end_time - $start_time ))
        if (( $time_diff < 10 )); then
            ((err_count += 1))
        else
            err_count=0
        fi
        [[ $err_count -gt 10 ]] && break

        echo "\r\e[1;33m[Disconnected. Retry ssh at $(date '+%F %T')...]\e[0m"
        sleep 1
    done

    # reset window name if we are in the tmux
    if [[ -n "$TMUX" ]]; then
        tmux set-window-option automatic-rename
    fi
    return $return_code
}

# Git
alias gws='gwS'


#
# fzf initialize
#

if [ -s ~/.fzf.zsh ]; then
    source ~/.fzf.zsh
fi
