[tools]
bun = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

ruby = "latest"
uv = "latest"

[settings]
minimum_release_age = "7d"

[settings.npm]
bun = true
package_manager = "bun"

[settings.ruby]
compile = false
